apiVersion: argoproj.io/v1alpha1
kind: AppProyect
metadata:
  name: apit-dev
  namespace: argocd
spec:
  project: default
  sourceRepos:
    - repoURL: https://github.com/mmuniz0/gitops-apps.git
      path: api
      targetRevision: dev
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: api