apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your/repo.git
    path: static
    targetRevision: stage
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: static